#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}"\
  -p "${BASEDIR}/dotbot-yarn/yarn.py" \
  -p "${BASEDIR}/dotbot-pacaur/pacaur.py" \
  -p "${BASEDIR}/dotbot-espanso/espanso.py" \
  -c "${CONFIG}" "${@}"
